namespace VLC_WinRT.Model
{
    public enum VLCPage
    {
        None,
        MainPageVideo,
        MainPageMusic,
        MainPageFileExplorer,
        MainPageNetwork,
        AlbumPage,
        ArtistPage,
        PlaylistPage,
        CurrentPlaylistPage,
        VideoPlayerPage,
        MusicPlayerPage,
        SettingsPage,
        SpecialThanksPage,
        ArtistShowsPage,
        AddAlbumToPlaylistDialog,
        CreateNewPlaylistDialog,
        LicensePage,
        SearchPage,
        MiniPlayerView,
        SettingsPageUI,
        SettingsPageMusic,
        SettingsPageVideo,
        VideoPlayerOptionsPanel,
        TrackEditorPage,
        FeedbackPage
    }
}
