namespace VLC.Model
{
    public enum Languages
    {
        English,
        French,
        Japanese,
        German,
        Polish,
        Slovak,
        Danish,
        Spanish,
        Hungarian,
        Italian,
        Korean,
        Malay,
        Norwegian,
        Dutch,
        Russian,
        Swedish,
        Turkish,
        Ukrainian,
        Chinese,
        Portuguese,
        Czech,
        Icelandic,
        Hebrew,
        Romanian,
        Brazilian,
        Arabic
    }
}
