namespace VLC.Model
{
    public enum VLCPage
    {
        None,
        MainPageVideo,
        MainPageMusic,
        MainPageFileExplorer,
        MainPageNetwork,
        AlbumPage,
        ArtistPage,
        ArtistInfoView,
        PlaylistPage,
        CurrentPlaylistPage,
        VideoPlayerPage,
        MusicPlayerPage,
        SettingsPage,
        ArtistShowsPage,
        AddAlbumToPlaylistDialog,
        CreateNewPlaylistDialog,
        SearchPage,
        MiniPlayerView,
        SettingsPageUI,
        SettingsPageMusic,
        SettingsPageVideo,
        VideoPlayerOptionsPanel,
        TrackEditorPage,
        FeedbackPage,
        TvShowView,
        AboutAppView,
        MainPageXBOX,
        ExternalStorageInclude,
    }
}
